// Code generated by $ go generate - DO NOT EDIT.

package limits

const (
	XAIO_PRIO_DELTA_MAX            = 20
	XBC_BASE_MAX                   = 99
	XBC_DIM_MAX                    = 2048
	XBC_SCALE_MAX                  = 99
	XBC_STRING_MAX                 = 1000
	XCHARCLASS_NAME_MAX            = 2048
	XCHAR_BIT                      = 8
	XCHAR_MAX                      = 127
	XCHAR_MIN                      = -128
	XCOLL_WEIGHTS_MAX              = 255
	XDELAYTIMER_MAX                = 2147483647
	XEXPR_NEST_MAX                 = 32
	XHOST_NAME_MAX                 = 64
	XINT_MAX                       = 2147483647
	XINT_MIN                       = -2147483648
	XLINE_MAX                      = 2048
	XLLONG_MAX                     = 9223372036854775807
	XLLONG_MIN                     = -9223372036854775808
	XLOGIN_NAME_MAX                = 256
	XLONG_MAX                      = 9223372036854775807
	XLONG_MIN                      = -9223372036854775808
	XMAX_CANON                     = 255
	XMAX_INPUT                     = 255
	XMB_LEN_MAX                    = 16
	XMQ_PRIO_MAX                   = 32768
	XNAME_MAX                      = 255
	XNGROUPS_MAX                   = 65536
	XPATH_MAX                      = 4096
	XPIPE_BUF                      = 4096
	XPTHREAD_DESTRUCTOR_ITERATIONS = 4
	XPTHREAD_KEYS_MAX              = 1024
	XPTHREAD_STACK_MIN             = 16384
	XRE_DUP_MAX                    = 32767
	XRTSIG_MAX                     = 32
	XSCHAR_MAX                     = 127
	XSCHAR_MIN                     = -128
	XSEM_VALUE_MAX                 = 2147483647
	XSHRT_MAX                      = 32767
	XSHRT_MIN                      = -32768
	XSSIZE_MAX                     = 9223372036854775807
	XTTY_NAME_MAX                  = 32
	XUCHAR_MAX                     = 255
	XUINT_MAX                      = 4294967295
	XULLONG_MAX                    = 18446744073709551615
	XULONG_MAX                     = 18446744073709551615
	XUSHRT_MAX                     = 65535
	XXATTR_LIST_MAX                = 65536
	XXATTR_NAME_MAX                = 255
	XXATTR_SIZE_MAX                = 65536
)
