// Code generated by $ go generate - DO NOT EDIT.

package stdio

const (
	XBUFSIZ       = 8192
	XEOF          = -1
	XFILENAME_MAX = 4096
	XFOPEN_MAX    = 16
	XL_ctermid    = 9
	XL_tmpnam     = 20
	XP_tmpdir     = "/tmp"
	XSEEK_CUR     = 1
	XSEEK_END     = 2
	XSEEK_SET     = 0
	XTMP_MAX      = 238328
	Xfscanf       = 0
	Xscanf        = 0
	Xsscanf       = 0
	Xvfscanf      = 0
	Xvscanf       = 0
	Xvsscanf      = 0
)
