// Code generated by $ go generate - DO NOT EDIT.

package stdio

const (
	XBUFSIZ              = 512
	XEOF                 = -1
	XFILENAME_MAX        = 260
	XFOPEN_MAX           = 20
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XP_tmpdir            = "\\"
	XSEEK_CUR            = 1
	XSEEK_END            = 2
	XSEEK_SET            = 0
	XSTDERR_FILENO       = 2
	XSTDIN_FILENO        = 0
	XSTDOUT_FILENO       = 1
	XSYS_OPEN            = 20
	XTMP_MAX             = 32767
	XUSE___UUIDOF        = 1
	Xpclose              = 0
	Xpopen               = 0
	Xwpopen              = 0
)
