// Code generated by $ go generate - DO NOT EDIT.

package malloc

const (
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XUSE___UUIDOF        = 1
	Xalloca              = 0
)
