// Code generated by $ go generate - DO NOT EDIT.

package malloc

const (
	XBUFSIZ           = 8192
	XEOF              = -1
	XFILENAME_MAX     = 4096
	XFOPEN_MAX        = 16
	XL_ctermid        = 9
	XL_tmpnam         = 20
	XM_ARENA_MAX      = -8
	XM_ARENA_TEST     = -7
	XM_CHECK_ACTION   = -5
	XM_GRAIN          = 3
	XM_KEEP           = 4
	XM_MMAP_MAX       = -4
	XM_MMAP_THRESHOLD = -3
	XM_MXFAST         = 1
	XM_NLBLKS         = 2
	XM_PERTURB        = -6
	XM_TOP_PAD        = -2
	XM_TRIM_THRESHOLD = -1
	XP_tmpdir         = "/tmp"
	XSEEK_CUR         = 1
	XSEEK_END         = 2
	XSEEK_SET         = 0
	XTMP_MAX          = 238328
	Xfscanf           = 0
	Xscanf            = 0
	Xsscanf           = 0
	Xvfscanf          = 0
	Xvscanf           = 0
	Xvsscanf          = 0
)
