// Code generated by $ go generate - DO NOT EDIT.

package pthread

const (
	XBIG_ENDIAN                    = 4321
	XBYTE_ORDER                    = 1234
	XCLOCK_BOOTTIME                = 7
	XCLOCK_BOOTTIME_ALARM          = 9
	XCLOCK_MONOTONIC               = 1
	XCLOCK_MONOTONIC_COARSE        = 6
	XCLOCK_MONOTONIC_RAW           = 4
	XCLOCK_PROCESS_CPUTIME_ID      = 2
	XCLOCK_REALTIME                = 0
	XCLOCK_REALTIME_ALARM          = 8
	XCLOCK_REALTIME_COARSE         = 5
	XCLOCK_TAI                     = 11
	XCLOCK_THREAD_CPUTIME_ID       = 3
	XLITTLE_ENDIAN                 = 1234
	XPDP_ENDIAN                    = 3412
	XPTHREAD_BARRIER_SERIAL_THREAD = -1
	XPTHREAD_ONCE_INIT             = 0
	XSCHED_FIFO                    = 1
	XSCHED_OTHER                   = 0
	XSCHED_RR                      = 2
	XTIMER_ABSTIME                 = 1

	CPTHREAD_CANCEL_ASYNCHRONOUS                  = 1
	CPTHREAD_CANCEL_DEFERRED                      = 0
	CPTHREAD_CANCEL_DISABLE                       = 1
	CPTHREAD_CANCEL_ENABLE                        = 0
	CPTHREAD_CREATE_DETACHED                      = 1
	CPTHREAD_CREATE_JOINABLE                      = 0
	CPTHREAD_EXPLICIT_SCHED                       = 1
	CPTHREAD_INHERIT_SCHED                        = 0
	CPTHREAD_MUTEX_ADAPTIVE_NP                    = 3
	CPTHREAD_MUTEX_DEFAULT                        = 0
	CPTHREAD_MUTEX_ERRORCHECK                     = 2
	CPTHREAD_MUTEX_ERRORCHECK_NP                  = 2
	CPTHREAD_MUTEX_NORMAL                         = 0
	CPTHREAD_MUTEX_RECURSIVE                      = 1
	CPTHREAD_MUTEX_RECURSIVE_NP                   = 1
	CPTHREAD_MUTEX_ROBUST                         = 1
	CPTHREAD_MUTEX_ROBUST_NP                      = 1
	CPTHREAD_MUTEX_STALLED                        = 0
	CPTHREAD_MUTEX_STALLED_NP                     = 0
	CPTHREAD_MUTEX_TIMED_NP                       = 0
	CPTHREAD_PRIO_INHERIT                         = 1
	CPTHREAD_PRIO_NONE                            = 0
	CPTHREAD_PRIO_PROTECT                         = 2
	CPTHREAD_PROCESS_PRIVATE                      = 0
	CPTHREAD_PROCESS_SHARED                       = 1
	CPTHREAD_RWLOCK_DEFAULT_NP                    = 0
	CPTHREAD_RWLOCK_PREFER_READER_NP              = 0
	CPTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP = 2
	CPTHREAD_RWLOCK_PREFER_WRITER_NP              = 1
	CPTHREAD_SCOPE_PROCESS                        = 1
	CPTHREAD_SCOPE_SYSTEM                         = 0
)
