// Code generated by $ go generate - DO NOT EDIT.

package io

const (
	XF_OK                = 0
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XR_OK                = 4
	XUSE___UUIDOF        = 1
	XW_OK                = 2
	XX_OK                = 1
	X_finddata_t         = 0
	X_finddatai64_t      = 0
	X_findfirst          = 0
	X_findfirsti64       = 0
	X_findnext           = 0
	X_findnexti64        = 0
	X_wfinddata_t        = 0
	X_wfinddatai64_t     = 0
	X_wfindfirst         = 0
	X_wfindfirsti64      = 0
	X_wfindnext          = 0
	X_wfindnexti64       = 0
	Xstrcasecmp          = 0
	Xstrncasecmp         = 0
	Xwcswcs              = 0
)
