// Code generated by $ go generate - DO NOT EDIT.

package ctype

const (
	XBIG_ENDIAN    = 4321
	XBYTE_ORDER    = 1234
	XLITTLE_ENDIAN = 1234
	XPDP_ENDIAN    = 3412

	X_ISalnum  = 8
	X_ISalpha  = 1024
	X_ISblank  = 1
	X_IScntrl  = 2
	X_ISdigit  = 2048
	X_ISgraph  = 32768
	X_ISlower  = 512
	X_ISprint  = 16384
	X_ISpunct  = 4
	X_ISspace  = 8192
	X_ISupper  = 256
	X_ISxdigit = 4096
)
