// Code generated by $ go generate - DO NOT EDIT.

package ctype

const (
	XBIG_ENDIAN    = 4321
	XBYTE_ORDER    = 1234
	XLITTLE_ENDIAN = 1234
	XPDP_ENDIAN    = 3412

	C_ISalnum  = 8
	C_ISalpha  = 1024
	C_ISblank  = 1
	C_IScntrl  = 2
	C_ISdigit  = 2048
	C_ISgraph  = 32768
	C_ISlower  = 512
	C_ISprint  = 16384
	C_ISpunct  = 4
	C_ISspace  = 8192
	C_ISupper  = 256
	C_ISxdigit = 4096
)
