// Code generated by $ go generate - DO NOT EDIT.

package ctype

const (
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XUSE___UUIDOF        = 1
	Xisascii             = 0
	Xiscsym              = 0
	Xiscsymf             = 0
	Xtoascii             = 0
)
