// Code generated by $ go generate - DO NOT EDIT.

package fts

const (
	XBIG_ENDIAN          = 4321
	XBYTE_ORDER          = 1234
	XFD_SETSIZE          = 1024
	XFTS_AGAIN           = 1
	XFTS_COMFOLLOW       = 1
	XFTS_D               = 1
	XFTS_DC              = 2
	XFTS_DEFAULT         = 3
	XFTS_DNR             = 4
	XFTS_DONTCHDIR       = 1
	XFTS_DOT             = 5
	XFTS_DP              = 6
	XFTS_ERR             = 7
	XFTS_F               = 8
	XFTS_FOLLOW          = 2
	XFTS_INIT            = 9
	XFTS_LOGICAL         = 2
	XFTS_NAMEONLY        = 256
	XFTS_NOCHDIR         = 4
	XFTS_NOINSTR         = 3
	XFTS_NOSTAT          = 8
	XFTS_NS              = 10
	XFTS_NSOK            = 11
	XFTS_OPTIONMASK      = 255
	XFTS_PHYSICAL        = 16
	XFTS_ROOTLEVEL       = 0
	XFTS_ROOTPARENTLEVEL = -1
	XFTS_SEEDOT          = 32
	XFTS_SKIP            = 4
	XFTS_SL              = 12
	XFTS_SLNONE          = 13
	XFTS_STOP            = 512
	XFTS_SYMFOLLOW       = 2
	XFTS_W               = 14
	XFTS_WHITEOUT        = 128
	XFTS_XDEV            = 64
	XLITTLE_ENDIAN       = 1234
	XPDP_ENDIAN          = 3412
)
