// Code generated by $ go generate - DO NOT EDIT.

package math

const (
	XEDOM                = 33
	XERANGE              = 34
	XFP_INFINITE         = 1280
	XFP_NAN              = 256
	XFP_NORMAL           = 1024
	XFP_SUBNORMAL        = 17408
	XFP_ZERO             = 16384
	XHUGE_VALF           = 0
	XHUGE_VALL           = 0
	XINFINITY            = 0
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XNAN                 = 0
	XUSE___UUIDOF        = 1
	X_hypotl             = 0
	Xmatherr             = 0
)
