// Code generated by $ go generate - DO NOT EDIT.

package math

const (
	XBIG_ENDIAN       = 4321
	XBYTE_ORDER       = 1234
	XDOMAIN           = 1
	XFP_ILOGB0        = -2147483648
	XFP_ILOGBNAN      = -2147483648
	XFP_INFINITE      = 1
	XFP_NAN           = 0
	XFP_NORMAL        = 4
	XFP_SUBNORMAL     = 3
	XFP_ZERO          = 2
	XHUGE             = 3.4028235e+38
	XLITTLE_ENDIAN    = 1234
	XMATH_ERREXCEPT   = 2
	XMATH_ERRNO       = 1
	XM_1_PI           = 0.3183098861837907
	XM_2_PI           = 0.6366197723675814
	XM_2_SQRTPI       = 1.1283791670955126
	XM_E              = 2.718281828459045
	XM_LN10           = 2.302585092994046
	XM_LN2            = 0.6931471805599453
	XM_LOG10E         = 0.4342944819032518
	XM_LOG2E          = 1.4426950408889634
	XM_PI             = 3.141592653589793
	XM_PI_2           = 1.5707963267948966
	XM_PI_4           = 0.7853981633974483
	XM_SQRT1_2        = 0.7071067811865476
	XM_SQRT2          = 1.4142135623730951
	XOVERFLOW         = 3
	XPDP_ENDIAN       = 3412
	XPLOSS            = 6
	XSING             = 2
	XTLOSS            = 5
	XUNDERFLOW        = 4
	XX_TLOSS          = 1.414847550405688e+16
	Xmath_errhandling = 3

	CFP_INFINITE  = 1
	CFP_NAN       = 0
	CFP_NORMAL    = 4
	CFP_SUBNORMAL = 3
	CFP_ZERO      = 2
	C_IEEE_       = -1
	C_ISOC_       = 3
	C_POSIX_      = 2
	C_SVID_       = 0
	C_XOPEN_      = 1
)
