// Code generated by $ go generate - DO NOT EDIT.

package mman

const (
	XMADV_DODUMP           = 17
	XMADV_DOFORK           = 11
	XMADV_DONTDUMP         = 16
	XMADV_DONTFORK         = 10
	XMADV_DONTNEED         = 4
	XMADV_FREE             = 8
	XMADV_HUGEPAGE         = 14
	XMADV_HWPOISON         = 100
	XMADV_MERGEABLE        = 12
	XMADV_NOHUGEPAGE       = 15
	XMADV_NORMAL           = 0
	XMADV_RANDOM           = 1
	XMADV_REMOVE           = 9
	XMADV_SEQUENTIAL       = 2
	XMADV_UNMERGEABLE      = 13
	XMADV_WILLNEED         = 3
	XMAP_32BIT             = 64
	XMAP_ANON              = 32
	XMAP_ANONYMOUS         = 32
	XMAP_DENYWRITE         = 2048
	XMAP_EXECUTABLE        = 4096
	XMAP_FILE              = 0
	XMAP_FIXED             = 16
	XMAP_GROWSDOWN         = 256
	XMAP_HUGETLB           = 262144
	XMAP_HUGE_MASK         = 63
	XMAP_HUGE_SHIFT        = 26
	XMAP_LOCKED            = 8192
	XMAP_NONBLOCK          = 65536
	XMAP_NORESERVE         = 16384
	XMAP_POPULATE          = 32768
	XMAP_PRIVATE           = 2
	XMAP_SHARED            = 1
	XMAP_STACK             = 131072
	XMAP_TYPE              = 15
	XMCL_CURRENT           = 1
	XMCL_FUTURE            = 2
	XMCL_ONFAULT           = 4
	XMS_ASYNC              = 1
	XMS_INVALIDATE         = 2
	XMS_SYNC               = 4
	XPOSIX_MADV_DONTNEED   = 4
	XPOSIX_MADV_NORMAL     = 0
	XPOSIX_MADV_RANDOM     = 1
	XPOSIX_MADV_SEQUENTIAL = 2
	XPOSIX_MADV_WILLNEED   = 3
	XPROT_EXEC             = 4
	XPROT_GROWSDOWN        = 16777216
	XPROT_GROWSUP          = 33554432
	XPROT_NONE             = 0
	XPROT_READ             = 1
	XPROT_WRITE            = 2
)
