// Code generated by $ go generate - DO NOT EDIT.

package dirent

const (
	XAIO_PRIO_DELTA_MAX            = 20
	XDELAYTIMER_MAX                = 2147483647
	XHOST_NAME_MAX                 = 64
	XLOGIN_NAME_MAX                = 256
	XMAXNAMLEN                     = 255
	XMAX_CANON                     = 255
	XMAX_INPUT                     = 255
	XMQ_PRIO_MAX                   = 32768
	XNAME_MAX                      = 255
	XNGROUPS_MAX                   = 65536
	XPATH_MAX                      = 4096
	XPIPE_BUF                      = 4096
	XPTHREAD_DESTRUCTOR_ITERATIONS = 4
	XPTHREAD_KEYS_MAX              = 1024
	XPTHREAD_STACK_MIN             = 16384
	XRTSIG_MAX                     = 32
	XSEM_VALUE_MAX                 = 2147483647
	XSSIZE_MAX                     = 0
	XTTY_NAME_MAX                  = 32
	XXATTR_LIST_MAX                = 65536
	XXATTR_NAME_MAX                = 255
	XXATTR_SIZE_MAX                = 65536
	Xd_fileno                      = 0

	CDT_BLK     = 6
	CDT_CHR     = 2
	CDT_DIR     = 4
	CDT_FIFO    = 1
	CDT_LNK     = 10
	CDT_REG     = 8
	CDT_SOCK    = 12
	CDT_UNKNOWN = 0
	CDT_WHT     = 14
)
