// Code generated by $ go generate - DO NOT EDIT.

package dirent

const (
	XAIO_PRIO_DELTA_MAX            = 20
	XDELAYTIMER_MAX                = 2147483647
	XHOST_NAME_MAX                 = 64
	XLOGIN_NAME_MAX                = 256
	XMAXNAMLEN                     = 255
	XMAX_CANON                     = 255
	XMAX_INPUT                     = 255
	XMQ_PRIO_MAX                   = 32768
	XNAME_MAX                      = 255
	XNGROUPS_MAX                   = 65536
	XPATH_MAX                      = 4096
	XPIPE_BUF                      = 4096
	XPTHREAD_DESTRUCTOR_ITERATIONS = 4
	XPTHREAD_KEYS_MAX              = 1024
	XPTHREAD_STACK_MIN             = 16384
	XRTSIG_MAX                     = 32
	XSEM_VALUE_MAX                 = 2147483647
	XSSIZE_MAX                     = 0
	XTTY_NAME_MAX                  = 32
	XXATTR_LIST_MAX                = 65536
	XXATTR_NAME_MAX                = 255
	XXATTR_SIZE_MAX                = 65536
	Xd_fileno                      = 0

	XDT_BLK     = 6
	XDT_CHR     = 2
	XDT_DIR     = 4
	XDT_FIFO    = 1
	XDT_LNK     = 10
	XDT_REG     = 8
	XDT_SOCK    = 12
	XDT_UNKNOWN = 0
	XDT_WHT     = 14
)
