// Code generated by $ go generate - DO NOT EDIT.

package wchar

const (
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XUSE___UUIDOF        = 1
	XWCHAR_MAX           = 65535
	XWCHAR_MIN           = 0
	X_fstat              = 0
	X_fstati64           = 0
	X_stat               = 0
	X_stati64            = 0
	X_wfinddata_t        = 0
	X_wfinddatai64_t     = 0
	X_wfindfirst         = 0
	X_wfindfirsti64      = 0
	X_wfindnext          = 0
	X_wfindnexti64       = 0
	X_wstat              = 0
	X_wstati64           = 0
	Xfstat64             = 0
	Xstat64              = 0
	Xwcswcs              = 0
	Xwpopen              = 0
)
