// Code generated by $ go generate - DO NOT EDIT.

package wchar

const (
	XWCHAR_MAX = 4294967295
	XWCHAR_MIN = 0
	XWEOF      = 4294967295
	Xfwscanf   = 0
	Xswscanf   = 0
	Xvfwscanf  = 0
	Xvswscanf  = 0
	Xvwscanf   = 0
	Xwscanf    = 0
)
