// Code generated by $ go generate - DO NOT EDIT.

package stdlib

const (
	XCHAR_BIT            = 8
	XCHAR_MAX            = 127
	XCHAR_MIN            = -128
	XEXIT_FAILURE        = 1
	XEXIT_SUCCESS        = 0
	XINT_MAX             = 2147483647
	XINT_MIN             = -2147483648
	XLLONG_MAX           = 9223372036854775807
	XLLONG_MIN           = -9223372036854775808
	XLONG_MAX            = 2147483647
	XLONG_MIN            = -2147483648
	XMB_LEN_MAX          = 1
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XRAND_MAX            = 32767
	XSCHAR_MAX           = 127
	XSCHAR_MIN           = -128
	XSHRT_MAX            = 32767
	XSHRT_MIN            = -32768
	XUCHAR_MAX           = 255
	XUINT_MAX            = 4294967295
	XULLONG_MAX          = 18446744073709551615
	XULONG_MAX           = 4294967295
	XUSE___UUIDOF        = 1
	XUSHRT_MAX           = 65535
	Xalloca              = 0
	Xonexit_t            = 0
	Xstrtod              = 0
	Xsys_errlist         = 0
	Xsys_nerr            = 0
)
