// Code generated by $ go generate - DO NOT EDIT.

package stdlib

const (
	XBIG_ENDIAN    = 4321
	XBYTE_ORDER    = 1234
	XEXIT_FAILURE  = 1
	XEXIT_SUCCESS  = 0
	XFD_SETSIZE    = 1024
	XLITTLE_ENDIAN = 1234
	XPDP_ENDIAN    = 3412
	XRAND_MAX      = 2147483647
	XWCONTINUED    = 8
	XWEXITED       = 4
	XWNOHANG       = 1
	XWNOWAIT       = 16777216
	XWSTOPPED      = 2
	XWUNTRACED     = 2

	XP_ALL  = 0
	XP_PGID = 2
	XP_PID  = 1
)
