// Code generated by $ go generate - DO NOT EDIT.

package in6addr

const (
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XUSE___UUIDOF        = 1
	Xin_addr6            = 0
)
