#ifdef __FLT_EVAL_METHOD__
#define FLT_EVAL_METHOD __FLT_EVAL_METHOD__
#else
#define FLT_EVAL_METHOD 2
#endif

#define LDBL_TRUE_MIN DBL_TRUE_MIN
#define LDBL_MIN     DBL_MIN
#define LDBL_MAX     DBL_MAX
#define LDBL_EPSILON DBL_EPSILON

#define LDBL_MANT_DIG DBL_MANT_DIG
#define LDBL_MIN_EXP DBL_MIN_EXP
#define LDBL_MAX_EXP DBL_MAX_EXP

#define LDBL_DIG DBL_DIG
#define LDBL_MIN_10_EXP DBL_MIN_10_EXP
#define LDBL_MAX_10_EXP DBL_MAX_10_EXP

#define DECIMAL_DIG DBL_DECIMAL_DIG
