// Code generated by $ go generate - DO NOT EDIT.

package intrin

const (
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XUSE___UUIDOF        = 1
	X_rotl64             = 0
	X_rotr64             = 0
)
