// Code generated by $ go generate - DO NOT EDIT.

package time

const (
	XCLK_TCK             = 1000
	XCLOCKS_PER_SEC      = 1000
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XUSE___UUIDOF        = 1
	X_timeb              = 0
)
