// Code generated by $ go generate - DO NOT EDIT.

package process

const (
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XOLD_P_OVERLAY       = 2
	XP_DETACH            = 4
	XP_NOWAIT            = 1
	XP_NOWAITO           = 3
	XP_OVERLAY           = 2
	XP_WAIT              = 0
	XUSE___UUIDOF        = 1
	XWAIT_CHILD          = 0
	XWAIT_GRANDCHILD     = 1
)
