// Code generated by $ go generate - DO NOT EDIT.

package stat

const (
	XF_OK                = 0
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XR_OK                = 4
	XS_IEXEC             = 64
	XS_IFBLK             = 12288
	XS_IFCHR             = 8192
	XS_IFDIR             = 16384
	XS_IFIFO             = 4096
	XS_IFMT              = 61440
	XS_IFREG             = 32768
	XS_IREAD             = 256
	XS_IRGRP             = 32
	XS_IRUSR             = 256
	XS_IRWXG             = 56
	XS_IRWXU             = 448
	XS_IWGRP             = 16
	XS_IWRITE            = 128
	XS_IWUSR             = 128
	XS_IXGRP             = 8
	XS_IXUSR             = 64
	XUSE___UUIDOF        = 1
	XW_OK                = 2
	XX_OK                = 1
	X_finddata_t         = 0
	X_finddatai64_t      = 0
	X_findfirst          = 0
	X_findfirsti64       = 0
	X_findnext           = 0
	X_findnexti64        = 0
	X_fstat              = 0
	X_fstati64           = 0
	X_stat               = 0
	X_stati64            = 0
	X_wfinddata_t        = 0
	X_wfinddatai64_t     = 0
	X_wfindfirst         = 0
	X_wfindfirsti64      = 0
	X_wfindnext          = 0
	X_wfindnexti64       = 0
	X_wstat              = 0
	X_wstati64           = 0
	Xfstat64             = 0
	Xstat64              = 0
	Xstrcasecmp          = 0
	Xstrncasecmp         = 0
	Xwcswcs              = 0
)
