// Code generated by $ go generate - DO NOT EDIT.

package locale

const (
	XLC_ADDRESS             = 9
	XLC_ADDRESS_MASK        = 512
	XLC_ALL                 = 6
	XLC_COLLATE             = 3
	XLC_COLLATE_MASK        = 8
	XLC_CTYPE               = 0
	XLC_CTYPE_MASK          = 1
	XLC_GLOBAL_LOCALE       = -1
	XLC_IDENTIFICATION      = 12
	XLC_IDENTIFICATION_MASK = 4096
	XLC_MEASUREMENT         = 11
	XLC_MEASUREMENT_MASK    = 2048
	XLC_MESSAGES            = 5
	XLC_MESSAGES_MASK       = 32
	XLC_MONETARY            = 4
	XLC_MONETARY_MASK       = 16
	XLC_NAME                = 8
	XLC_NAME_MASK           = 256
	XLC_NUMERIC             = 1
	XLC_NUMERIC_MASK        = 2
	XLC_PAPER               = 7
	XLC_PAPER_MASK          = 128
	XLC_TELEPHONE           = 10
	XLC_TELEPHONE_MASK      = 1024
	XLC_TIME                = 2
	XLC_TIME_MASK           = 4
)
