// Code generated by $ go generate - DO NOT EDIT.

package locale

const (
	XLC_ALL              = 0
	XLC_COLLATE          = 1
	XLC_CTYPE            = 2
	XLC_MAX              = 5
	XLC_MIN              = 0
	XLC_MONETARY         = 3
	XLC_NUMERIC          = 4
	XLC_TIME             = 5
	XMINGW_DDRAW_VERSION = 7
	XMINGW_HAS_DDK_H     = 1
	XMINGW_HAS_DDRAW_H   = 1
	XUSE___UUIDOF        = 1
)
